BEGIN 

INSERT INTO source_column_master_base (
COLUMN_NAME, COLUMN_TYPE, CONCATENATED_FIELD, IS_DELETED, LANG_ID, LM_DECODE_COLUMN, LM_JOIN_COLUMN,
LM_JOIN_EQUI_OUTER, LM_TABLE_NAME_ATM_ID, PRIMARY_KEY_ID, REPORT_ITEM, TABLE_NAME_ATM_ID, DECODE_COLUMN, DELETED
)
VALUES 
(
'FLAG_IND_SUBMISSION', 'N', NULL, 0, '*', 'STATE_YN', 'ID', 'O', 'VW_CLP_STATE_YN', NULL, 'VCMAC_FLAG_IND_SUBMISSION', 'V_C_MASTER_ADDL_CSTM', NULL, NULL
);

INSERT INTO source_column_master_base (
COLUMN_NAME, COLUMN_TYPE, CONCATENATED_FIELD, IS_DELETED, LANG_ID, LM_DECODE_COLUMN, LM_JOIN_COLUMN,
LM_JOIN_EQUI_OUTER, LM_TABLE_NAME_ATM_ID, PRIMARY_KEY_ID, REPORT_ITEM, TABLE_NAME_ATM_ID, DECODE_COLUMN, DELETED
)
VALUES 
(
'FLAG_NDA_SUBMISSION', 'N', NULL, 0, '*', 'STATE_YN', 'ID', 'O', 'VW_CLP_STATE_YN', NULL, 'VCMAC_FLAG_NDA_SUBMISSION', 'V_C_MASTER_ADDL_CSTM', NULL, NULL
);

INSERT INTO source_column_master_base (
COLUMN_NAME, COLUMN_TYPE, CONCATENATED_FIELD, IS_DELETED, LANG_ID, LM_DECODE_COLUMN, LM_JOIN_COLUMN,
LM_JOIN_EQUI_OUTER, LM_TABLE_NAME_ATM_ID, PRIMARY_KEY_ID, REPORT_ITEM, TABLE_NAME_ATM_ID, DECODE_COLUMN, DELETED
)
VALUES 
(
'FLAG_PERIODIC_SUBMISSION', 'N', NULL, 0, '*', 'STATE_YN', 'ID', 'O', 'VW_CLP_STATE_YN', NULL, 'VCMAC_FLAG_PERIODIC_SUBMISSION', 'V_C_MASTER_ADDL_CSTM', NULL, NULL
);

INSERT INTO source_column_master_base (
COLUMN_NAME, COLUMN_TYPE, CONCATENATED_FIELD, IS_DELETED, LANG_ID, LM_DECODE_COLUMN, LM_JOIN_COLUMN,
LM_JOIN_EQUI_OUTER, LM_TABLE_NAME_ATM_ID, PRIMARY_KEY_ID, REPORT_ITEM, TABLE_NAME_ATM_ID, DECODE_COLUMN, DELETED
)
VALUES 
(
'FLAG_LP_SUBMISSION', 'N', NULL, 0, '*', 'STATE_YN', 'ID', 'O', 'VW_CLP_STATE_YN', NULL, 'VCMAC_FLAG_LP_SUBMISSION', 'V_C_MASTER_ADDL_CSTM', NULL, NULL
);

INSERT INTO source_column_master_base (
COLUMN_NAME, COLUMN_TYPE, CONCATENATED_FIELD, IS_DELETED, LANG_ID, LM_DECODE_COLUMN, LM_JOIN_COLUMN,
LM_JOIN_EQUI_OUTER, LM_TABLE_NAME_ATM_ID, PRIMARY_KEY_ID, REPORT_ITEM, TABLE_NAME_ATM_ID, DECODE_COLUMN, DELETED
)
VALUES 
(
'FLAG_INVALID', 'N', NULL, 0, '*', 'STATE_YN', 'ID', 'O', 'VW_CLP_STATE_YN', NULL, 'VCMAC_FLAG_INVALID', 'V_C_MASTER_ADDL_CSTM', NULL, NULL
); 

END;
/