BEGIN 

INSERT INTO case_column_join_mapping_base(COLUMN_NAME,IS_DELETED, MAP_COLUMN_NAME, MAP_TABLE_NAME_ATM_ID, TABLE_NAME_ATM_ID) 
VALUES 
(
'CASE_ID', 0, 'CASE_ID', 'V_C_IDENTIFICATION', 'V_C_MASTER_ADDL_CSTM'
);

COMMIT;

END;
/