BEGIN 

INSERT INTO source_table_master_base  
(
CASE_JOIN_EQUI_OUTER, CASE_JOIN_ORDER, HAS_ENTERPRISE_ID, IS_DELETED, RANK_COLUMN, TABLE_ALIAS, 
TABLE_NAME, TABLE_TYPE, VERSIONED_DATA, DELETED, PRIMARY_KEY
) 
VALUES 
(
'E', 2, 1, 0, NULL, 'vcmac', 'V_C_MASTER_ADDL_CSTM', 'C', 'V', NULL, 'TENANT_ID,CASE_ID,VERSION_NUM'
); 

COMMIT;

END;
/
