BEGIN 

INSERT INTO rpt_field_base (
DATA_TYPE, DATE_FORMAT, DESCRIPTION, DIC_LEVEL, DIC_TYPE, FIXED_WIDTH, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT,
 LIST_DOMAIN_CLASS, LMSQL, NAME, POST_QUERY_PROCEDURE, PRE_QUERY_PROCEDURE, PRE_REPORT_PROCEDURE, QUERY_SELECTABLE,
  RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE,
   TRANSFORM, VERSION, WIDTH_PROPORTION_INDEX, ML_FLAG
) 
VALUES 
(
'java.lang.String', 'app.dateformat.truncDate', NULL, NULL, NULL, NULL, 0,0,0, 'com.rxlogix.TableColumnSelectableList', 'app.dropdown.VwclpstateynStateyn', 'vcmacFlagIndSubmission', 
NULL, NULL, NULL,  1, 'CaseInformation', 'VCMAC_FLAG_IND_SUBMISSION', 1, 1, 1, 'vcmacFlagIndSubmission', 0, NULL, 0 
);
 
INSERT INTO rpt_field_base (
DATA_TYPE, DATE_FORMAT, DESCRIPTION, DIC_LEVEL, DIC_TYPE, FIXED_WIDTH, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT,
 LIST_DOMAIN_CLASS, LMSQL, NAME, POST_QUERY_PROCEDURE, PRE_QUERY_PROCEDURE, PRE_REPORT_PROCEDURE, QUERY_SELECTABLE,
  RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE,
   TRANSFORM, VERSION, WIDTH_PROPORTION_INDEX, ML_FLAG
) 
VALUES 
(
'java.lang.String', 'app.dateformat.truncDate', NULL, NULL, NULL, NULL, 0,0,0, 'com.rxlogix.TableColumnSelectableList', 'app.dropdown.VwclpstateynStateyn', 'vcmacFlagNdaSubmission', 
NULL, NULL, NULL,  1, 'CaseInformation', 'VCMAC_FLAG_NDA_SUBMISSION', 1, 1, 1, 'vcmacFlagNdaSubmission', 0, NULL, 0 
);

INSERT INTO rpt_field_base (
DATA_TYPE, DATE_FORMAT, DESCRIPTION, DIC_LEVEL, DIC_TYPE, FIXED_WIDTH, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT,
 LIST_DOMAIN_CLASS, LMSQL, NAME, POST_QUERY_PROCEDURE, PRE_QUERY_PROCEDURE, PRE_REPORT_PROCEDURE, QUERY_SELECTABLE,
  RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE,
   TRANSFORM, VERSION, WIDTH_PROPORTION_INDEX, ML_FLAG
) 
VALUES 
(
'java.lang.String', 'app.dateformat.truncDate', NULL, NULL, NULL, NULL, 0,0,0, 'com.rxlogix.TableColumnSelectableList', 'app.dropdown.VwclpstateynStateyn', 'vcmacFlagPeriodicSubmission', 
NULL, NULL, NULL,  1, 'CaseInformation', 'VCMAC_FLAG_PERIODIC_SUBMISSION', 1, 1, 1, 'vcmacFlagPeriodicSubmission', 0, NULL, 0 
);

INSERT INTO rpt_field_base (
DATA_TYPE, DATE_FORMAT, DESCRIPTION, DIC_LEVEL, DIC_TYPE, FIXED_WIDTH, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT,
 LIST_DOMAIN_CLASS, LMSQL, NAME, POST_QUERY_PROCEDURE, PRE_QUERY_PROCEDURE, PRE_REPORT_PROCEDURE, QUERY_SELECTABLE,
  RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE,
   TRANSFORM, VERSION, WIDTH_PROPORTION_INDEX, ML_FLAG
) 
VALUES 
(
'java.lang.String', 'app.dateformat.truncDate', NULL, NULL, NULL, NULL, 0,0,0, 'com.rxlogix.TableColumnSelectableList', 'app.dropdown.VwclpstateynStateyn', 'vcmacFlagLpSubmission', 
NULL, NULL, NULL,  1, 'CaseInformation', 'VCMAC_FLAG_LP_SUBMISSION', 1, 1, 1, 'vcmacFlagLpSubmission', 0, NULL, 0 
);

INSERT INTO rpt_field_base (
DATA_TYPE, DATE_FORMAT, DESCRIPTION, DIC_LEVEL, DIC_TYPE, FIXED_WIDTH, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT,
 LIST_DOMAIN_CLASS, LMSQL, NAME, POST_QUERY_PROCEDURE, PRE_QUERY_PROCEDURE, PRE_REPORT_PROCEDURE, QUERY_SELECTABLE,
  RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE,
   TRANSFORM, VERSION, WIDTH_PROPORTION_INDEX, ML_FLAG
) 
VALUES 
(
'java.lang.String', 'app.dateformat.truncDate', NULL, NULL, NULL, NULL, 0,0,0, 'com.rxlogix.TableColumnSelectableList', 'app.dropdown.VwclpstateynStateyn', 'vcmacflaginvalid', 
NULL, NULL, NULL,  1, 'CaseInformation', 'VCMAC_FLAG_INVALID', 1, 1, 1, 'vcmacflaginvalid', 0, NULL, 0 
);


END;
/