BEGIN
   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql,
                NAME, post_query_procedure, pre_query_procedure,
                pre_report_procedure, query_selectable, rpt_field_grpname,
                source_column_master_id, templt_cll_selectable,
                templt_dtcol_selectable, templt_dtrow_selectable, transform,
                VERSION, width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.CludfmrcalculatedDescription',
                'popMarketingProgram', NULL, NULL,
                NULL, 1, 'CaseInformation',
                'CM_POP_MARKETING_PROGRAM', 1,
                1, 1, 'popMarketingProgram',
                0, NULL, NULL
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME,
                post_query_procedure, pre_query_procedure,
                pre_report_procedure, query_selectable, rpt_field_grpname,
                source_column_master_id, templt_cll_selectable,
                templt_dtcol_selectable, templt_dtrow_selectable, transform,
                VERSION, width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.VwclpstateynStateyn', 'caseMasterPmsStudies',
                NULL, NULL,
                NULL, 1, 'CaseInformation',
                'CM_PMS_STUDIES', 1,
                1, 1, 'caseMasterPmsStudies',
                0, NULL, NULL
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME,
                post_query_procedure, pre_query_procedure,
                pre_report_procedure, query_selectable, rpt_field_grpname,
                source_column_master_id, templt_cll_selectable,
                templt_dtcol_selectable, templt_dtrow_selectable, transform,
                VERSION, width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.VwclpstateynStateyn', 'mostRelevantEvent',
                NULL, NULL,
                NULL, 1, 'EventInformation',
                'CM_MOST_RELEVANT_EVENT', 1,
                1, 1, 'mostRelevantEvent',
                0, NULL, NULL
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'diagnosisSymptom', NULL,
                NULL, NULL, 1,
                'EventInformation', 'CM_DIAGNOSIS_SYMPTOM',
                1, 1,
                1, 'diagnosisSymptom', 0,
                NULL, NULL
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'lpudaUdText6J', NULL,
                NULL, NULL, 1,
                'CaseInformation', 'LPUDA_UD_TEXT_6_J',
                1, 0,
                0, 'lpudaUdText6J', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'lpudaUdText5J', NULL,
                NULL, NULL, 1,
                'ReporterInformation', 'LPUDA_UD_TEXT_5_J',
                1, 0,
                0, 'lpudaUdText5J', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.vwtradeLicenseType', 'ceaLicenseType', NULL,
                NULL, NULL, 1,
                'PmdaLicenseInformation', 'CEA_LICENSE_TYPE',
                1, 1,
                1, 'ceaLicenseType', 0,
                NULL, 0
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.vwtradeLicenseTypeJ', 'ceaLicenseTypeJ', NULL,
                NULL, NULL, 1,
                'PmdaLicenseInformation', 'CEA_LICENSE_TYPE_J',
                1, 1,
                1, 'ceaLicenseTypeJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'casePatInfoUdText1J', NULL,
                NULL, NULL, 1,
                'PatientInformation', 'CASE_PAT_INFO_UD_TEXT_1_J',
                1, 0,
                0, 'casePatInfoUdText1J', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.util.Date', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'cpudaUdDate01', NULL,
                NULL, NULL, 1,
                'ReporterInformation', 'CPUDA_UD_DATE_1',
                1, 0,
                0, 'cpudaUdDate01', 0,
                NULL, 0
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.util.Date', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'cpudaUdDate02', NULL,
                NULL, NULL, 1,
                'CaseInformation', 'CPUDA_UD_DATE_2',
                1, 0,
                0, 'cpudaUdDate02', 0,
                NULL, 0
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, NULL, 0, 0,
                NULL, NULL, 'masterSuspGenericListJ', NULL,
                NULL, NULL, 0,
                'ProductInformation', 'CPRODJ_SUSP_GENERIC_LIST_J',
                1, 0,
                0, 'masterSuspGenericListJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, NULL, 0, 0,
                NULL, NULL, 'masterConcGenericListJ', NULL,
                NULL, NULL, 0,
                'ProductInformation', 'CPRODJ_CONC_GENERIC_LIST_J',
                1, 0,
                0, 'masterConcGenericListJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'cpatiPatCompPtCodeJ', NULL,
                NULL, NULL, 1,
                'PatientInformation', 'CPATI_PAT_COMP_PT_CODE_J',
                1, 0,
                0, 'cpatiPatCompPtCodeJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'gsectSector', NULL,
                'p_insert_gtt_sector', NULL, 1,
                'CaseInformation', 'GSECT_SECTOR',
                1, 0,
                0, 'gsectSector', 0,
                NULL, 0
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.VwclpstateynStateyn', 'crPrimCorrSource', NULL,
                NULL, NULL, 1,
                'ReportInformation', 'CR_PRIM_CORR_SOURCE',
                1, 0,
                0, 'crPrimCorrSource', 0,
                NULL, NULL
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME,
                post_query_procedure, pre_query_procedure,
                pre_report_procedure, query_selectable, rpt_field_grpname,
                source_column_master_id, templt_cll_selectable,
                templt_dtcol_selectable, templt_dtrow_selectable, transform,
                VERSION, width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.VwclpstateynStateynJ', 'crPrimCorrSourceJ',
                NULL, NULL,
                NULL, 1, 'ReportInformation',
                'CR_PRIM_CORR_SOURCE_J', 1,
                0, 0, 'crPrimCorrSourceJ',
                0, NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'vcmadTaskCommentDescJ', NULL,
                NULL, NULL, 1,
                'CaseActivityInformation', 'VCMAD_TASK_COMMENT_DESC_J',
                1, 0,
                0, 'vcmadTaskCommentDescJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'vcmadPartnerNameJ', NULL,
                NULL, NULL, 1,
                'ReporterInformation', 'VCMAD_PARTNER_NAME_J',
                1, 0,
                0, 'vcmadPartnerNameJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'vcmadDeletedDeactivatedJ', NULL,
                NULL, NULL, 1,
                'CaseInformation', 'VCMAD_DELETED_DEACTIVATED_J',
                1, 0,
                0, 'vcmadDeletedDeactivatedJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.util.Date', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'vcmadLockDateGlobalJ', NULL,
                NULL, NULL, 1,
                'CaseRoutingInformation', 'VCMAD_LOCK_DATE_GLOBAL_J',
                1, 0,
                0, 'vcmadLockDateGlobalJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.util.Date', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'vcmadLockDateLocalJ', NULL,
                NULL, NULL, 1,
                'CaseRoutingInformation', 'VCMAD_LOCK_DATE_LOCAL_J',
                1, 0,
                0, 'vcmadLockDateLocalJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.VwclpstateynStateyn', 'rraPmdaFlag', NULL,
                NULL, NULL, 1,
                'PmdaLicenseInformation', 'RRA_PMDA_FLAG',
                1, 0,
                0, 'rraPmdaFlag', 0,
                NULL, NULL
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class,
                lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                'com.rxlogix.TableColumnSelectableList',
                'app.dropdown.VwclpstateynStateynJ', 'rraPmdaFlagJ', NULL,
                NULL, NULL, 1,
                'PmdaLicenseInformation', 'RRA_PMDA_FLAG_J',
                1, 0,
                0, 'rraPmdaFlagJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, description, dic_level,
                dic_type, fixed_width, isautocomplete, is_deleted, is_text,
                list_domain_class, lmsql, NAME, post_query_procedure,
                pre_query_procedure, pre_report_procedure, query_selectable,
                rpt_field_grpname, source_column_master_id,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, VERSION,
                width_proportion_index, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL, 0, 0, 0,
                NULL, NULL, 'vcmadPmdaSubmissionsJ', NULL,
                NULL, NULL, 1,
                'PmdaLicenseInformation', 'VCMAD_PMDA_SUBMISSIONS_J',
                1, 0,
                0, 'vcmadPmdaSubmissionsJ', 0,
                NULL, 1
               );

   INSERT INTO rpt_field_base
               (source_column_master_id, NAME,
                data_type, rpt_field_grpname, query_selectable,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, list_domain_class, lmsql,
                isautocomplete, DATE_FORMAT, dic_level, dic_type,
                post_query_procedure, pre_query_procedure,
                pre_report_procedure, width_proportion_index, fixed_width,
                VERSION, is_deleted, is_text, ml_flag
               )
        VALUES ('CPATI_PAT_COMORBIDITY_J', 'cpatiPatComorbidityJ',
                'java.lang.String', 'PatientInformation', 1,
                1, 0,
                0, 'cpatiPatComorbidityJ', NULL, NULL,
                0, 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL,
                NULL, NULL, NULL,
                0, 0, 0, 1
               );

   INSERT INTO rpt_field_base
               (source_column_master_id, NAME,
                data_type, rpt_field_grpname, query_selectable,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, list_domain_class, lmsql,
                isautocomplete, DATE_FORMAT, dic_level, dic_type,
                post_query_procedure, pre_query_procedure,
                pre_report_procedure, width_proportion_index, fixed_width,
                VERSION, is_deleted, is_text, ml_flag
               )
        VALUES ('CPATI_PAT_ANON_PT_CODE_J', 'cpatiPatAnonPtCodeJ',
                'java.lang.String', 'PatientInformation', 1,
                1, 0,
                0, 'cpatiPatAnonPtCodeJ', NULL, NULL,
                0, 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL,
                NULL, NULL, NULL,
                0, 0, 0, 1
               );

   INSERT INTO rpt_field_base
               (source_column_master_id, NAME,
                data_type, rpt_field_grpname, query_selectable,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, list_domain_class, lmsql,
                isautocomplete, DATE_FORMAT, dic_level, dic_type,
                post_query_procedure, pre_query_procedure,
                pre_report_procedure, width_proportion_index, fixed_width,
                VERSION, is_deleted, is_text, ml_flag
               )
        VALUES ('CPATI_PAT_PAST_DISEASE_J', 'cpatiPatPastDiseaseJ',
                'java.lang.String', 'PatientInformation', 1,
                1, 0,
                0, 'cpatiPatPastDiseaseJ', NULL, NULL,
                0, 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL,
                NULL, NULL, NULL,
                0, 0, 0, 1
               );

   INSERT INTO rpt_field_base
               (source_column_master_id,
                NAME, data_type,
                rpt_field_grpname, query_selectable, templt_cll_selectable,
                templt_dtcol_selectable, templt_dtrow_selectable, transform,
                list_domain_class, lmsql, isautocomplete, DATE_FORMAT,
                dic_level, dic_type, post_query_procedure,
                pre_query_procedure, pre_report_procedure,
                width_proportion_index, fixed_width, VERSION, is_deleted,
                is_text, ml_flag
               )
        VALUES ('CPATI_OTHER_TRTMNT_HIST_PT_CODE_J',
                'cpatiOtherTrtmntHistPtCodeJ', 'java.lang.String',
                'PatientInformation', 1, 1,
                0, 0, 'cpatiOtherTrtmntHistPtCodeJ',
                NULL, NULL, 0, 'app.dateformat.truncDate',
                NULL, NULL, NULL,
                NULL, NULL,
                NULL, NULL, 0, 0,
                0, 1
               );

   INSERT INTO rpt_field_base
               (source_column_master_id, NAME,
                data_type, rpt_field_grpname, query_selectable,
                templt_cll_selectable, templt_dtcol_selectable,
                templt_dtrow_selectable, transform, list_domain_class, lmsql,
                isautocomplete, DATE_FORMAT, dic_level, dic_type,
                post_query_procedure, pre_query_procedure,
                pre_report_procedure, width_proportion_index, fixed_width,
                VERSION, is_deleted, is_text, ml_flag
               )
        VALUES ('CPATI_PAT_OTHER_TRTMNT_HIST_J', 'cpatiPatOtherTrtmntHistJ',
                'java.lang.String', 'PatientInformation', 1,
                1, 0,
                0, 'cpatiPatOtherTrtmntHistJ', NULL, NULL,
                0, 'app.dateformat.truncDate', NULL, NULL,
                NULL, NULL,
                NULL, NULL, NULL,
                0, 0, 0, 1
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, isautocomplete, is_deleted, is_text,
                NAME, query_selectable, rpt_field_grpname,
                source_column_master_id, templt_cll_selectable,
                templt_dtcol_selectable, templt_dtrow_selectable, transform,
                VERSION
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', 0, 0, 0,
                'cpudaUdNumber09', 1, 'ReportInformation',
                'CPUDA_UD_NUMBER_9', 1,
                0, 0, 'cpudaUdNumber09',
                0
               );

   INSERT INTO rpt_field_base
               (data_type, DATE_FORMAT, isautocomplete, is_deleted, is_text,
                NAME, query_selectable, rpt_field_grpname,
                source_column_master_id, templt_cll_selectable,
                templt_dtcol_selectable, templt_dtrow_selectable, transform,
                VERSION, ml_flag
               )
        VALUES ('java.lang.String', 'app.dateformat.truncDate', 0, 0, 0,
                'cpudaUdNumber09J', 1, 'ReportInformation',
                'CPUDA_UD_NUMBER_9_J', 1,
                0, 0, 'cpudaUdNumber09J',
                0, 1
               );

   UPDATE rpt_field_base
      SET templt_cll_selectable = 1,
          query_selectable = 1
    WHERE NAME = 'casePatInfoPvrUdText1J';

   UPDATE rpt_field_base
      SET templt_dtrow_selectable = 1,
          templt_dtcol_selectable = 1,
          query_selectable = 1,
          templt_cll_selectable = 1
    WHERE source_column_master_id = 'CASE_EVENT_PVR_UD_TEXT_1_J';

   UPDATE rpt_field_base
      SET lmsql = 'app.dropdown.Vwclplcau'
    WHERE source_column_master_id = 'DCPE_CONSER_REPORTABILITY';

   UPDATE rpt_field_base
      SET lmsql = 'app.dropdown.VwclplcauJ'
    WHERE source_column_master_id = 'DCPE_CONSER_REPORTABILITY_J';

   UPDATE rpt_field_base
      SET data_type = 'java.lang.String'
    WHERE NAME = 'rpmaiReportTypeId';

   UPDATE rpt_field_base
      SET source_column_master_id = 'RPMAI_REPORT_TYPE_ID_J',
          data_type = 'java.lang.String'
    WHERE NAME = 'rpmaiReportTypeIdJ';

INSERT INTO RPT_FIELD_BASE (DATA_TYPE, DATE_FORMAT, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT, LIST_DOMAIN_CLASS, LMSQL, NAME, QUERY_SELECTABLE, RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, 
TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE, TRANSFORM, VERSION)
VALUES('java.lang.String', 'app.dateformat.truncDate',0,0,0,'com.rxlogix.TableColumnSelectableList','app.dropdown.vwEcrsMeddraTerm','ecrsMeddraTerm',1,'EcrsInformation','ECRS_MEDDRA_TERM',0,0,0,'ecrsMeddraTerm',0);
INSERT INTO RPT_FIELD_BASE (DATA_TYPE, DATE_FORMAT, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT, LIST_DOMAIN_CLASS, LMSQL, NAME, QUERY_SELECTABLE, RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, 
TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE, TRANSFORM, VERSION)
VALUES('java.lang.String', 'app.dateformat.truncDate',0,0,0,'com.rxlogix.TableColumnSelectableList','app.dropdown.vwEcrsRiskPurpose','ecrsRiskPurpose',1,'EcrsInformation','ECRS_RISK_PURPOSE',0,0,0,'ecrsRiskPurpose',0);
INSERT INTO RPT_FIELD_BASE (DATA_TYPE, DATE_FORMAT, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT, LIST_DOMAIN_CLASS, LMSQL, NAME, QUERY_SELECTABLE, RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, 
TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE, TRANSFORM, VERSION)
VALUES('java.lang.String', 'app.dateformat.truncDate',0,0,0,'com.rxlogix.TableColumnSelectableList','app.dropdown.vwEcrsNonCompound','ecrsNonCompound',1,'EcrsInformation','ECRS_NON_COMPOUND',1,0,0,'ecrsNonCompound',0);
INSERT INTO RPT_FIELD_BASE (DATA_TYPE, DATE_FORMAT, ISAUTOCOMPLETE, IS_DELETED, IS_TEXT, LIST_DOMAIN_CLASS, LMSQL, NAME, QUERY_SELECTABLE, RPT_FIELD_GRPNAME, SOURCE_COLUMN_MASTER_ID, 
TEMPLT_CLL_SELECTABLE, TEMPLT_DTCOL_SELECTABLE, TEMPLT_DTROW_SELECTABLE, TRANSFORM, VERSION)
VALUES('java.lang.String', 'app.dateformat.truncDate',0,0,0,NULL,NULL,'ecrsSafetyTopicOfInterest',0,'EventInformation','ECRS_SAFETY_TOPIC_OF_INTEREST',1,0,0,'ecrsSafetyTopicOfInterest',0);

Insert into RPT_FIELD_BASE (DATA_TYPE,DATE_FORMAT,DESCRIPTION,DIC_LEVEL,DIC_TYPE,FIXED_WIDTH,ISAUTOCOMPLETE,IS_DELETED,IS_TEXT,LIST_DOMAIN_CLASS,LMSQL,NAME,POST_QUERY_PROCEDURE,PRE_QUERY_PROCEDURE,PRE_REPORT_PROCEDURE,QUERY_SELECTABLE,RPT_FIELD_GRPNAME,SOURCE_COLUMN_MASTER_ID,TEMPLT_CLL_SELECTABLE,TEMPLT_DTCOL_SELECTABLE,TEMPLT_DTROW_SELECTABLE,TRANSFORM,VERSION,WIDTH_PROPORTION_INDEX,ML_FLAG) values ('java.lang.Number','app.dateformat.truncDate',null,null,null,null,0,0,0,null,null,'impactIndNumber',null,null,null,1,'CaseInformation','CS_IMPACT_IND_NUMBER',1,1,1,'impactIndNumber',0,null,null);
Insert into RPT_FIELD_BASE (DATA_TYPE,DATE_FORMAT,DESCRIPTION,DIC_LEVEL,DIC_TYPE,FIXED_WIDTH,ISAUTOCOMPLETE,IS_DELETED,IS_TEXT,LIST_DOMAIN_CLASS,LMSQL,NAME,POST_QUERY_PROCEDURE,PRE_QUERY_PROCEDURE,PRE_REPORT_PROCEDURE,QUERY_SELECTABLE,RPT_FIELD_GRPNAME,SOURCE_COLUMN_MASTER_ID,TEMPLT_CLL_SELECTABLE,TEMPLT_DTCOL_SELECTABLE,TEMPLT_DTROW_SELECTABLE,TRANSFORM,VERSION,WIDTH_PROPORTION_INDEX,ML_FLAG) values ('java.lang.String','app.dateformat.truncDate',null,null,null,null,0,0,0,'com.rxlogix.TableColumnSelectableList','app.dropdown.vdinfclinicaltrialimp01','impactNonIntegrated',null,null,null,1,'CaseInformation','CS_IMPACT_NON_INTEGRATED',1,1,1,'impactNonIntegrated',0,null,null);
Insert into RPT_FIELD_BASE (DATA_TYPE,DATE_FORMAT,DESCRIPTION,DIC_LEVEL,DIC_TYPE,FIXED_WIDTH,ISAUTOCOMPLETE,IS_DELETED,IS_TEXT,LIST_DOMAIN_CLASS,LMSQL,NAME,POST_QUERY_PROCEDURE,PRE_QUERY_PROCEDURE,PRE_REPORT_PROCEDURE,QUERY_SELECTABLE,RPT_FIELD_GRPNAME,SOURCE_COLUMN_MASTER_ID,TEMPLT_CLL_SELECTABLE,TEMPLT_DTCOL_SELECTABLE,TEMPLT_DTROW_SELECTABLE,TRANSFORM,VERSION,WIDTH_PROPORTION_INDEX,ML_FLAG) values ('java.lang.String','app.dateformat.truncDate',null,null,null,null,0,0,0,null,null,'impactStudyNcc',null,null,null,1,'CaseInformation','CS_IMPACT_STUDY_NCC_CODES',1,1,1,'impactStudyNcc',0,null,null);
Insert into RPT_FIELD_BASE (DATA_TYPE,DATE_FORMAT,DESCRIPTION,DIC_LEVEL,DIC_TYPE,FIXED_WIDTH,ISAUTOCOMPLETE,IS_DELETED,IS_TEXT,LIST_DOMAIN_CLASS,LMSQL,NAME,POST_QUERY_PROCEDURE,PRE_QUERY_PROCEDURE,PRE_REPORT_PROCEDURE,QUERY_SELECTABLE,RPT_FIELD_GRPNAME,SOURCE_COLUMN_MASTER_ID,TEMPLT_CLL_SELECTABLE,TEMPLT_DTCOL_SELECTABLE,TEMPLT_DTROW_SELECTABLE,TRANSFORM,VERSION,WIDTH_PROPORTION_INDEX,ML_FLAG) values ('java.lang.String','app.dateformat.truncDate',null,null,null,null,0,0,0,null,null,'impactProjectNcc',null,null,null,1,'CaseInformation','CS_IMPACT_PROJECT_NCC_CODES',1,1,1,'impactProjectNcc',0,null,null);	

   COMMIT;
END;
/