begin
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.popMarketingProgram','en','POP Marketing Program');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.caseMasterPmsStudies','en','PMS Studies');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.mostRelevantEvent','en','Most Relevant Event');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.diagnosisSymptom','en','Diagnosis : Symptom');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.lpudaUdText6J','en','DSE J Receipt Date History');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.lpudaUdText6J','ja','DSE入手日歴');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.lpudaUdText5J','en','MR Sent Date History');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.lpudaUdText5J','ja','MR送信日歴');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.ceaLicenseTypeJ','en','License Type (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.ceaLicenseTypeJ','ja','ケースレシート日付J');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.ceaLicenseType','en','License Type');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.ceaLicenseType','ja','ケースレシート日付J (E)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.dropdown.vwtradeLicenseTypeJ','*','select distinct license_type  from VW_TRADE_COUNTRY_J');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.dropdown.vwtradeLicenseType','*','select distinct license_type  from VW_TRADE_COUNTRY');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.cpudaUdDate01','en','MR Sent Date');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.cpudaUdDate01','ja','MR送信日');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.cpudaUdDate02','en','DSE J Receipt Date');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.cpudaUdDate02','ja','DSE入手日');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.masterSuspGenericListJ','en','Blinded Suspect Products - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.masterSuspGenericListJ','ja','盲検被疑薬 - 全て');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.masterConcGenericListJ','en','Blinded Concomitant Products - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.masterConcGenericListJ','ja','盲検併用薬 - 全て');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.cpatiPatCompPtCodeJ','en','Current Condition PT Code - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.cpatiPatCompPtCodeJ','ja','合併症PTコード');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.gsectSector','en','Sector (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.gsectSector','ja','部門');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.crPrimCorrSource','en','Primary Correspondent');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.crPrimCorrSource','ja','一次送付先 (E)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.crPrimCorrSourceJ','en','Primary Correspondent (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.crPrimCorrSourceJ','ja','一次送付先');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadTaskCommentDescJ','en','Action Item Code (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadTaskCommentDescJ','ja','再調査要否');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadPartnerNameJ','en','Partner Name (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadPartnerNameJ','ja','一提携会社名');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadDeletedDeactivatedJ','en','Deleted-Deactivated (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadDeletedDeactivatedJ','ja','削除済み - 無効化済み');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadLockDateGlobalJ','en','Case Lock Date and Time - Global (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadLockDateGlobalJ','ja','英語画面のロック日');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadLockDateLocalJ','en','Case Lock Date and Time - Japan (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadLockDateLocalJ','ja','日本語画面のロック日');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.rraPmdaFlag','en','Last Unsubmitted PMDA Reports');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.rraPmdaFlag','ja','PMDA未提出報告 (E)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.rraPmdaFlagJ','en','Last Unsubmitted PMDA Reports (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.rraPmdaFlagJ','ja','PMDA未提出報告');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadPmdaSubmissionsJ','en','PMDA Submission Dates (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.vcmadPmdaSubmissionsJ','ja','PMDA報告日');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.dropdown.Vwclplcau','*','select distinct CAUSALITY from VW_LCAU_CONS_CAUSALITY  where CAUSALITY is not null order by upper(CAUSALITY) Asc');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.dropdown.VwclplcauJ','*','select distinct CAUSALITY from VW_LCAU_CONS_CAUSALITY_J  where CAUSALITY is not null order by upper(CAUSALITY) Asc');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatComorbidityJ', 'en', 'Current Condition PT - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatComorbidityJ', 'ja', '合併症');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatAnonPtCodeJ', 'en', 'Historical Condition PT Code - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatAnonPtCodeJ', 'ja', '既往症PTコード');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatPastDiseaseJ', 'en', 'Historical Condition PT - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatPastDiseaseJ', 'ja', '既往症');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiOtherTrtmntHistPtCodeJ', 'en', 'Other Medical History PT code - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiOtherTrtmntHistPtCodeJ', 'ja', 'その他治療歴PTコード');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatOtherTrtmntHistJ', 'en', 'Other Medical History PT - All (J)');
Insert into PVR_RPT_FIELD_LABEL_BASE
   (CODE, 
    LOC, TEXT)
 Values
   ('app.reportField.cpatiPatOtherTrtmntHistJ', 'ja', 'その他治療歴');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.cpudaUdNumber09','en','15/30 Day Report');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.cpudaUdNumber09','ja','15日/30日報告(E)');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.cpudaUdNumber09J','en','15/30 Day Report(J)');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.cpudaUdNumber09J','ja','15日/30日報告');

UPDATE PVR_RPT_FIELD_LABEL_BASE
   SET text = 'CPO Japan use only(E)'
 WHERE code LIKE '%caseEventPvrUdText1J';

INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.ecrsMeddraTerm','*','ECRS Meddra Term');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportFieldGroup.EcrsCompoundInformation','*','ECRS Compound Information');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.dropdown.vwEcrsMeddraTerm','*','select distinct MEDDRA_TERM from VW_ECRS_MEDDRA_TERM where MEDDRA_TERM is not null order by upper(MEDDRA_TERM) Asc');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.ecrsRiskPurpose','*','ECRS Risk Purpose List');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.dropdown.vwEcrsRiskPurpose','*','select distinct RISK_PURPOSE_LIST from VW_ECRS_RISK_PURPOSE_DROP where RISK_PURPOSE_LIST is not null order by upper(RISK_PURPOSE_LIST) Asc');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportFieldGroup.EcrsInformation','*','ECRS Information');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.ecrsNonCompound','*','ECRS Non Compound');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.dropdown.vwEcrsNonCompound','*','select distinct SAFETY_TOPIC_OF_INTEREST from VW_ECRS_NON_COMPOUND where SAFETY_TOPIC_OF_INTEREST is not null order by upper(SAFETY_TOPIC_OF_INTEREST) Asc');
INSERT INTO PVR_RPT_FIELD_LABEL_BASE (CODE, LOC, TEXT)
VALUES ('app.reportField.ecrsSafetyTopicOfInterest','*','Safety Topic Of Interest - ECRS');

Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.impactIndNumber','en','Ind Number (Impact)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.impactNonIntegrated','en','Non Integrated Cases (Impact)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.dropdown.vdinfclinicaltrialimp01','*','Select distinct CASE_NON_INTEGRATED_IN from V_DINF_CLINICAL_TRIAL_IMP01');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.impactStudyNcc','*','Study NCC Codes (Impact)');
Insert into PVR_RPT_FIELD_LABEL_BASE (CODE,LOC,TEXT) values ('app.reportField.impactProjectNcc','*','Project NCC Codes (Impact)');

COMMIT;
end;
/