--Enter the database name
--DEFINE DB=''
DEFINE DB='PVMQ01'
--Enter name for STAGE USER
DEFINE USERST='pvd_stage'
--Enter name for MART USER
DEFINE USERTX='pvd_hub'
--Enter name for DB APP USER
DEFINE USERRX='pvr_db_app'
--Enter name for CUSTOM STAGE USER
DEFINE USERUT='pvd_stage_cstm'
--Enter name for CUSTOM MART USER
DEFINE USERVX='pvd_hub_cstm'
--Enter name for PV_ANALYTICS USER [default: PV_ANALYTICS]
DEFINE USERPVA = 'PV_ANALYTICS'
